include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    avoid_classes_with_only_static_members: false
    avoid_returning_null: false
    prefer_collection_literals: false